[versions]
slf4j-version = "2.0.0-alpha1"
logback-version = "1.3.0-alpha4"
picocli-version = "4.6.1"
jackson-version = "2.12.2"
nameascreated-version = "9.4"
jetbrains-annotations-version = "20.1.0"

[libraries]
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson-version" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-version" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-version" }
nameascreated = { group = "fr.raksrinana", name = "nameascreated", version.ref = "nameascreated-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }

[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]
